name: ci-example

on:
  push:
  pull_request:

jobs:
  test-file:
    runs-on: windows-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v6
    - name: Test File
      run: ./scripts/check-file.ps1
